sudo: required
services:
  - docker

before_install:
  - docker build -t sandeepvithanage/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sandeepvithanage/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  backet_name: "elasticbeanstalk-us-east-1-094317257354"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
