sudo: required
services:
  - docker

before_install:
  - docker build -t sandeepvithanage/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sandeepvithanage/docker-react npm run test
